[package]
name = "two-party-ecdsa"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = ["gmp-backend", "parallel", "secp256k1-backend", "typetag-support"]
gmp-backend = ["rust-gmp"]
num-bigint-backend = ["num-bigint", "num-traits", "num-integer", "getrandom/js"]
gmp-wasm-backend = ["num-bigint", "num-traits", "num-integer", "getrandom/js", "wasm-bindgen"]
parallel = ["rayon"]
secp256k1-backend = ["secp256k1"]
k256-backend = ["k256"]
typetag-support = ["dep:typetag"]

[dependencies]
rand = "0.8"
zeroize = "1"
sha3 = "0.10"
sha2 = "0.10"
hmac = "0.12"
rayon = { version = "1", optional = true }
serde = { version = "1.0.147", features = ["derive"] }
#serde_derive = "1.0"
itertools = "0.10"
bit-vec = "0.6"
typetag = { version = "0.2.3", optional = true }

[dependencies.rust-gmp]
version = "0.5.0"
features = ["serde_support"]
git = "https://github.com/KZen-networks/rust-gmp"
optional = true

[dependencies.secp256k1]
version = "0.21.0"
features = ["rand", "serde"]
optional = true

[dependencies.k256]
version = "0.13"
features = ["arithmetic"]
optional = true

[dependencies.num-bigint]
version = "0.4"
optional = true

[dependencies.num-traits]
version = "0.2"
optional = true

[dependencies.num-integer]
version = "0.1"
optional = true

[dependencies.getrandom]
version = "0.2"
optional = true

[dependencies.wasm-bindgen]
version = "0.2"
optional = true

[dev-dependencies]
serde_json = "1"
